# Generated by Django 3.2.7 on 2021-09-12 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models


def insert_default_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ETT = apps.get_model("events", "EventTypeTbl")

    for i, n in enumerate(('received', 'assigned', 'prepped')):
        e = ETT(name=n, index=i)
        e.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypeTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('color', events.models.ColorField(default='#ff4312', max_length=10)),
                ('index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventsTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=140, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type',
                 models.ForeignKey(db_column='event_typeID', on_delete=django.db.models.deletion.DO_NOTHING,
                                   to='events.eventtypetbl')),
                ('sample', models.ForeignKey(db_column='sampleID', on_delete=django.db.models.deletion.DO_NOTHING,
                                             to='samples.sampletbl')),
                ('user', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(insert_default_data)
    ]
