# Generated by Django 3.2.7 on 2021-09-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventstbl',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='eventstbl',
            name='event_at',
            field=models.DateTimeField(null=True),
        ),
    ]
