# Generated by Django 3.2.7 on 2021-09-27 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210913_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstbl',
            name='sample',
            field=models.ForeignKey(db_column='sampleID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='samples.sampletbl'),
        ),
        migrations.CreateModel(
            name='EventValuesTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_value', models.TextField()),
                ('int_value', models.IntegerField()),
                ('float_value', models.FloatField()),
                ('name', models.CharField(max_length=80)),
                ('event', models.ForeignKey(db_column='eventID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='values', to='events.eventstbl')),
            ],
        ),
    ]
