version: '3.8'

services:
  web:
    build: .
    command: gunicorn pychronweb.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.production
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web