version: '3.8'

services:
  web:
    restart: always
    build: ./web
    command: gunicorn pychronweb.wsgi:application -w 2 -b :8000 --reload -t 600
    volumes:
      - ./web:/home/app/web
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.production
    depends_on:
      - redis

  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

  redis:
    image: redis:alpine
  celery:
    build: ./web
    command: celery -A pychronweb worker -l info
    env_file:
      - ./.env.production
    environment:
      - DEBUG=1
#      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
#      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
    volumes:
      - ./web/:/home/app/web/
  celery-beat:
    build: ./web
    env_file:
      - ./.env.production
    command: celery -A pychronweb beat -l info
    volumes:
      - ./web/:/home/app/web/
    environment:
      - DEBUG=1
#      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
#      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis


volumes:
  static_volume: