# Generated by Django 3.2.7 on 2021-12-15 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='PackagesTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140, null=True)),
            ],

        ),
        migrations.CreateModel(
            name='PackageAssociationTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(db_column='packageID', on_delete=django.db.models.deletion.DO_NOTHING, to='packages.packagestbl')),
                ('sample', models.ForeignKey(db_column='sampleID', on_delete=django.db.models.deletion.DO_NOTHING, to='samples.sampletbl')),
            ],
        ),
    ]
