# Generated by Django 3.2.7 on 2021-09-05 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materialtbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('grainsize', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'MaterialTbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Principalinvestigatortbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140, null=True)),
                ('email', models.CharField(blank=True, max_length=140, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=140, null=True)),
                ('oid', models.IntegerField(blank=True, null=True)),
                ('last_name', models.CharField(blank=True, max_length=140, null=True)),
                ('first_initial', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'PrincipalInvestigatorTbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projecttbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('checkin_date', models.DateField(blank=True, null=True)),
                ('lab_contact', models.CharField(blank=True, max_length=80, null=True)),
                ('institution', models.CharField(blank=True, max_length=80, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ProjectTbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sampletbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('note', models.CharField(blank=True, max_length=140, null=True)),
                ('igsn', models.CharField(blank=True, max_length=140, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=140, null=True)),
                ('lithology', models.CharField(blank=True, max_length=140, null=True)),
                ('location', models.CharField(blank=True, max_length=140, null=True)),
                ('approximate_age', models.FloatField(blank=True, null=True)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('lithology_class', models.CharField(blank=True, max_length=140, null=True)),
                ('lithology_group', models.CharField(blank=True, max_length=140, null=True)),
                ('lithology_type', models.CharField(blank=True, max_length=140, null=True)),
                ('unit', models.CharField(blank=True, max_length=80, null=True)),
                ('materialid', models.ForeignKey(blank=True, db_column='materialID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='samples.materialtbl')),
                ('projectid', models.ForeignKey(blank=True, db_column='projectID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='samples.projecttbl')),
            ],
            options={
                'db_table': 'SampleTbl',
            },
        )
    ]
